version: "3.9"
services:
  drone-runner:
    build:
      args:
        ALPINE_VERSION: latest
        CONTAINER_VERSION: 1.7.0
        DRONE_RUNNER_EXEC_VERSION: 1.0.0-beta.10
        DRONE_CLI_VERSION: 1.7.0
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "drone-runner:build"
    environment:
      - SYSTEM_ENVIRONMENT=DEVELOPMENT
    hostname: "drone-runner"
    image: "gautada/drone-runner:build"
    privileged: true
    ports:
      - "3000:3000"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Volumes/container
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Volumes/backup
      
