#!/usr/bin/env python
import yaml

with open('docker-compose.yml', 'r') as f:
    compose_data = yaml.safe_load(f)

services = compose_data.get('services', {})

assert 1 == len(service), "ERROR: Only one(1) service expected in a container compose file."

for service_name in services:
    print(service_name)
    
