version: "3.9"
services:
  drone-runner:
    build:
      args:
        ALPINE_VERSION: latest
        CONTAINER_VERSION: 1.7.0
      context: .
      dockerfile: Containerfile
      no_cache: true  
      tags:
          - "drone-runner:build"
          - "gautada/drone-runner:build"
          - "gautada/drone-runner:latest"
      image: "gautada/drone-runner:latest"
    hostname: "drone-runner"
    ports:
      - "3000:3000"
    volumes:
      - "Container:/mnt/volumes/container"
      - "Backup:/mnt/volumes/backup"
      - "Secrets:/mnt/volumes/secrets"
      - "Configmaps:/mnt/volumes/configmaps"
      
