kind: pipeline
type: exec
name: CICD - Drone Runner Container

platform:
  os: linux
  arch: arm64

steps:
- name: build
  commands:
  - /usr/sbin/image-build
  - /usr/bin/podman images

- name: publish
  environment:
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
    PUBLISH_REPOSITORY: docker.io
    IMAGE_NAME: drone-runner
  commands:
  - /usr/bin/podman tag \
    localhost/$IMAGE_NAME:build \
    $PUBLISH_REPOSITORY/$DOCKERIO_USERNAME/$IMAGE_NAME:test
  - /usr/bin/podman login \
    --username=$DOCKERIO_USERNAME \
    --password=$DOCKERIO_PASSWORD \
    $PUBLISH_REPOSITORY
  - /usr/bin/podman push \
    $PUBLISH_REPOSITORY/$DOCKERIO_USERNAME/$IMAGE_NAME:test
  
- name: integrate
  environment:
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
  commands:
  - /usr/bin/podman tag \
    localhost/$IMAGE_NAME:build \
    $PUBLISH_REPOSITORY/$DOCKERIO_USERNAME/$IMAGE_NAME:1.0.0
  - /usr/bin/podman tag \
    localhost/$IMAGE_NAME:build \
    $PUBLISH_REPOSITORY/$DOCKERIO_USERNAME/$IMAGE_NAME:latest
  - /usr/bin/podman login \
    --username=$DOCKERIO_USERNAME \
    --password=$DOCKERIO_PASSWORD \
    $PUBLISH_REPOSITORY
  - /usr/bin/podman push \
    $PUBLISH_REPOSITORY/$DOCKERIO_USERNAME/$IMAGE_NAME:1.0.0
  - /usr/bin/podman push \
    $PUBLISH_REPOSITORY/$DOCKERIO_USERNAME/$IMAGE_NAME:latest
  when:
    branch:
    - main

trigger:
  event:
  - push
  
