kind: pipeline
type: exec
name: Drone Runner Container CICD

platform:
  os: linux
  arch: arm64

steps:
- name: build
  commands:
  - /usr/bin/podman-compose build $(/usr/bin/compose-data --name) --no-cache

- name: test
  commands:
  # /usr/bin/podman-compose run --detach $(/usr/bin/compose-service-name)
  - echo $(/usr/bin/compose-data)
  
- name: integrate
  environment:
    CONTAINER_NAME: "drone-runner"
    CONTAINER_VERSION: 1.7.0
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
  commands:
   - /usr/bin/podman tag $(/usr/bin/compose-data --name):build docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-data --name):$(/usr/bin/compose-data 
--version)
   - /usr/bin/podman tag $(/usr/bin/compose-data --name):build docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-data --name):latest
   - /usr/bin/podman login --username=$DOCKERIO_USERNAME --password=$DOCKERIO_PASSWORD docker.io
   - /usr/bin/podman push docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-data --name):$CONTAINER_VERSION
   - /usr/bin/podman push docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-data --name):$(/usr/bin/compose-data --version)

- name: deploy
  environment:
    KUBECONFIG: "/mnt/volumes/configmaps/kubeconfig"
    GIT_USERNAME:
      from_secret: username.git.gautier.org
    GIT_PASSWORD:
      from_secret: password.git.gautier.org
    CONTAINER_NAME: "drone-runner"
  commands:
  - ls -l
  # - git clone https://$GIT_USERNAME:$GIT_PASSWORD@git.gautier.org/Cluster/drone-runner-manifest.git manifest
  # - /bin/ls -l manifest/
  # - /usr/bin/kubectl apply -f manifest/configmap.yml
  # - /usr/bin/kubectl apply -f manifest/ingress.yml
  # - /usr/bin/kubectl apply -f manifest/service.yml
  # - /usr/bin/kubectl apply -f manifest/deployment.yml &
  
trigger:
  branch:
  - main
