#!/bin/sh

_NAME="$(/usr/sbin/image-name)"

/usr/bin/podman tag \
 "localhost/$_NAME:build" \
 "$PUBLISH_REPOSITORY/$DOCKERIO_USERNAME/$_NAME:$1"
 
/usr/bin/podman login \
  --username=$DOCKERIO_USERNAME \
  --password=$DOCKERIO_PASSWORD \
  $PUBLISH_REPOSITORY
 
/usr/bin/podman push \
 "$PUBLISH_REPOSITORY/$DOCKERIO_USERNAME/$_NAME:$1"

